libpipe: Parameters Class Reference
Parameters Class Reference
Classes
class InvalidParameterName
class InvalidParameterType
Public Member Functions
Parameters ()
Parameters (const std::vector< std::string > &required, const std::vector< std::string > &optional)
void addOptionalParameters (const std::string &optional)
void addRequiredParameters (const std::string &required)
bool count (const std::string &key) const
template<typename T >
const T get (const std::string &key)
template<typename T >
void set (const std::string &key, const T &value)
bool validate () const
Private Types
typedef std::map< std::string,
Variant > Map
typedef boost::variant
< std::string, std::vector
< std::string > > Variant
Private Member Functions
template<typename T >
const T get_impl (const std::string &key, T *)
template<typename T >
const std::vector< T > get_impl (const std::string &key, std::vector< T > *)
Private Attributes
std::vector< std::string > optionalParams_
Map params_
std::vector< std::string > requiredParams_
Detailed Description
Generic parameter collection class. The Parameters class is a (somewhat) generic collection of key/value pairs intended for use as a parameter object. The implementation is based on an underlying variant that can take any type but has currently been limited to
      std::string, std::vector<std::string> >
Using Parameters instances is straightforward, however there are a few best practices:
in most cases a Parameters instance will be part of e.g. a Filter or an algorithm class/object. In this case, the containing class should provide get functionality to a properly instantiated Parameters object, that has been initialized with the correct required and optional parameter names (i.e. keys) as well as set functionality for the complete Parameters instance.
     // SomeObject constructor:
     SomeObject::SomeObject(...) : ...
     {
         ...
         std::vector<std::string> req, opt;
         req.push_back("delta");
         opt.push_back("solution");
         params_ = Parameters(req, opt);
         ...
     }
in such cases, the client code should not attempt to construct a parameter object from scratch but instead copy the existing object:
    Parameters p = someObject.getParameters();
    p.set("delta", "0.773");
    p.set("solution", "42");
    someObject.setParameters(p);
before using the values in a Parameters object, the client should validate the contents to see if the required keys are present:
     ...
     bool isGood = p.validate();
     ...
     if (!isGood) {
         throw UnleashMayhem("Oops.");
     }
     ...
See the tests for more examples.
Definition at line 92 of file Parameters.hpp.
Member Typedef Documentation
typedef std::map<std::string, Variant> Map [private]
Typedef of Parameters Map
Definition at line 213 of file Parameters.hpp.
typedef boost::variant<std::string, std::vector<std::string> > Variant [private]
Possible types that can be stored by Parameters
Definition at line 202 of file Parameters.hpp.
Constructor & Destructor Documentation
Parameters () [explicit]
Explicit constructor to avoid implicit type conversions.
Definition at line 60 of file Parameters.cpp.
Parameters (const std::vector< std::string > & required, const std::vector< std::string > & optional)
Constructor.
Parameters:
[in] required The names (keys) of required parameters. These keys will be required for validate() to succeed.
[in] optional The names (keys) of required parameters.
Definition at line 64 of file Parameters.cpp.
Member Function Documentation
void addOptionalParameters (const std::string & optional)
Adds a new optinal Parameter to the Parameters
Parameters:
optional The name (key) of a additional optional parameter
Definition at line 94 of file Parameters.cpp.
References Parameters::optionalParams_, and vector< _Tp, _Alloc >::push_back().
void addRequiredParameters (const std::string & required)
Adds a new required Parameter to the Parameters
Parameters:
required The name (key) of a additional required parameter
Definition at line 89 of file Parameters.cpp.
References vector< _Tp, _Alloc >::push_back(), and Parameters::requiredParams_.
Referenced by ConfigJSON::parseInputFile().
bool count (const std::string & key) const
Check if a particular parameter name (i.e. key) exists.
Parameters:
key The key for which the check is requested.
Returns:
True if the key is found. Always false for invalid parameters.
Definition at line 70 of file Parameters.cpp.
References map< _Key, _Tp, _Compare, _Alloc >::count(), and Parameters::params_.
const T get (const std::string & key)
Retrieve the value for a specific key. Type conversion is implemented using the template parameter with boost::lexical_cast:
     ...
     Parameters p(req, opt);
     p.set("name", "someValue");
     std::string s = p.get<std::string>("name");
     ...
Parameters:
key The key of interest.
Returns:
A copy to the value associated with the key key.
Exceptions:
Throws InvalidParameterName if the key is not among the required or optional keys and InvalidParameterType if the requested type does not match the stored type.
Definition at line 269 of file Parameters.hpp.
References Parameters::get_impl().
Referenced by Source::update().
const T get_impl (const std::string & key, T *) [private]
Internal retrieve the value for a specific key. Type conversion is implemented using the template parameter:
Parameters:
key The key of interest.
Returns:
A copy to the value associated with the key key.
Exceptions:
Throws InvalidParameterName if the key is not among the required or optional keys and InvalidParameterType if the requested type does not match the stored type.
Definition at line 282 of file Parameters.hpp.
References map< _Key, _Tp, _Compare, _Alloc >::end(), map< _Key, _Tp, _Compare, _Alloc >::find(), and Parameters::params_.
Referenced by Parameters::get().
const std::vector< T > get_impl (const std::string & key, std::vector< T > *) [private]
Internal retrieve the value for a specific key. Type conversion is implemented using the template parameter: ...
Parameters:
key The key of interest.
Returns:
A copy to the value associated with the key key.
Exceptions:
Throws InvalidParameterName if the key is not among the required or optional keys and InvalidParameterType if the requested type does not match the stored type.
Definition at line 302 of file Parameters.hpp.
References vector< _Tp, _Alloc >::begin(), map< _Key, _Tp, _Compare, _Alloc >::end(), vector< _Tp, _Alloc >::end(), map< _Key, _Tp, _Compare, _Alloc >::find(), Parameters::params_, and vector< _Tp, _Alloc >::push_back().
void set (const std::string & key, const T & value)
Set a key/value pair.
Parameters:
key The key.
value The value.
Exceptions:
Throws InvalidParameterName if the key is not among the required or optional keys.
Definition at line 253 of file Parameters.hpp.
References vector< _Tp, _Alloc >::begin(), vector< _Tp, _Alloc >::end(), find(), Parameters::optionalParams_, Parameters::params_, Parameters::requiredParams_, and value().
Referenced by ConfigJSON::parseInputFile().
bool validate () const
Check if all required parameters have been set. This check if all required key have be associated with a value. Note that this does NOT check if the types of the values are correct (as the expected type is currently not stored).
Returns:
True if all required parameters are associated with a value.
Definition at line 75 of file Parameters.cpp.
References vector< _Tp, _Alloc >::begin(), map< _Key, _Tp, _Compare, _Alloc >::count(), vector< _Tp, _Alloc >::end(), Parameters::params_, and Parameters::requiredParams_.
Member Data Documentation
std::vector<std::string> optionalParams_ [private]
Storage of optional Parameters
Definition at line 209 of file Parameters.hpp.
Referenced by Parameters::addOptionalParameters(), and Parameters::set().
Map params_ [private]
Store the actual parameters
Definition at line 216 of file Parameters.hpp.
Referenced by Parameters::count(), Parameters::get_impl(), Parameters::set(), and Parameters::validate().
std::vector<std::string> requiredParams_ [private]
Storage of required Parameters
Definition at line 206 of file Parameters.hpp.
Referenced by Parameters::addRequiredParameters(), Parameters::set(), and Parameters::validate().
The documentation for this class was generated from the following files:
/Users/david/Desktop/ETHZ/1_Master/Boston/libpipe/include/libpipe/utilities/Parameters.hpp
/Users/david/Desktop/ETHZ/1_Master/Boston/libpipe/src/utilities/Parameters.cpp