libpipe: libpipe: BasicFilter< A, M > Class Template Reference
BasicFilter< A, M > Class Template Reference
Code related to the compile-time configuration
Public Member Functions
BasicFilter (const std::string &name)
virtual ~BasicFilter ()
virtual A * getAlgorithm ()
virtual M * getManager ()
std::string getName () const
virtual void processRequest (libpipe::Request &req)
void setName (const std::string &name)
Protected Member Functions
void setAlgorithm (Algorithm *alg)
void setManager (Manager *manager)
Detailed Description
template<class A, class M>
class libpipe::ctc::BasicFilter< A, M >
Wraps an algorithm and a manager into a Filter. This is the preferred way of creating a filter type from given Algorithm and Manager types. Assuming the user has implemented an algorithm in a class UserAlgorithm and makes use of the normal Manager, the corresponding filter is acquired using
 #include <libpipe/Manager.hpp>
 ...
 using namespace libpipe;
 ...
 typedef BasicFilter<UserAlgorithm, Manager> UserFilter;
 ...
The filter can then be used in the usual way:
 ...
 boost::shared_ptr<UserFilter> uf (new UserFilter("FilterName"));
 uf->getAlgorithm()->setParameters(...);
 ...
 uf->getManager()->connect(boost::dynamic_pointer_cast<Filter>(someOtherFilter->getManager()));
 uf->getAlgorithm()->setInputFoo(someOtherFilter->getAlgorithm()->getOutputBar());
 ...
Definition at line 64 of file BasicFilter.hpp.
Constructor & Destructor Documentation
BasicFilter (const std::string & name)
Constructor.
Parameters:
name The name of the filter. Passed through to libpipe::Filter.
Definition at line 97 of file BasicFilter.hpp.
References Filter::setAlgorithm(), and Filter::setManager().
~BasicFilter () [virtual]
Destructor. Virtual, to allow for subclassing.
Definition at line 107 of file BasicFilter.hpp.
Member Function Documentation
A * getAlgorithm () [virtual]
Provides access to the algorithm object. This is a small hack: we need to redefine getAlgorithm in each Filter because there is only a minimal fixed interface for Algorithm, that does not include all potential functions a user might add.
Returns:
A pointer (with the true class type) to the algorithm object.
Reimplemented from Filter.
Definition at line 112 of file BasicFilter.hpp.
References Filter::getAlgorithm().
M * getManager () [virtual]
Provides access to the manager object.
See also:
getAlgorithm.
Returns:
A pointer (with the true class type) to the manager object.
Reimplemented from Filter.
Definition at line 118 of file BasicFilter.hpp.
References Filter::getManager().
std::string getName () const [inherited]
Returns the name of the filter.
Returns:
The name of the filter.
Definition at line 86 of file Filter.cpp.
References Filter::name_.
Referenced by Filter::processRequest().
void processRequest (libpipe::Request & req) [virtual, inherited]
Processes a request. This method forwards the request to the Algorithm and Manager objects.
Parameters:
[in,out] req The request object.
Definition at line 45 of file Filter.cpp.
References Filter::getManager(), Filter::getName(), and Manager::processRequest().
void setAlgorithm (Algorithm * alg) [protected, inherited]
Set the algorithm that should be used for this filter.
Parameters:
[in] alg Pointer to the Algorithm object.
Definition at line 58 of file Filter.cpp.
References Filter::algorithm_, Filter::manager_, and Manager::setAlgorithm().
Referenced by BasicFilter< A, M >::BasicFilter().
void setManager (Manager * manager) [protected, inherited]
Set the manager that manages the filter.
Parameters:
[in] manager Pointer to the Manager object.
Definition at line 76 of file Filter.cpp.
References Filter::manager_.
Referenced by BasicFilter< A, M >::BasicFilter().
void setName (const std::string & name) [inherited]
Set the name of the filter.
Parameters:
[in] name The name of the filter.
Definition at line 91 of file Filter.cpp.
References Filter::name_.
The documentation for this class was generated from the following file:
/home/mkirchner/src/libpipe/include/libpipe/ctc/BasicFilter.hpp