libpipe: libpipe: Algorithm Class Reference
Algorithm Class Reference
Code related to the compile-time configuration
Public Member Functions
Algorithm ()
virtual ~Algorithm ()=0
const timeval & getMTime () const
bool needUpdate () const
void processRequest (Request &req)
void setMTime (const timeval &tv)
virtual void update (Request &req)=0
void updateMTime ()
Static Public Attributes
static const timeval MAX_TIME
static const timeval MIN_TIME
Static Private Member Functions
static timeval initMaxTime ()
static timeval initMinTime ()
Private Attributes
timeval mTime_
Detailed Description
Base class for all libpipe algorithms that support runtime configuration.
Definition at line 52 of file Algorithm.hpp.
Constructor & Destructor Documentation
Algorithm ()
Constructor.
Definition at line 55 of file Algorithm.cpp.
~Algorithm () [pure virtual]
Pure virtual descructor.
Definition at line 60 of file Algorithm.cpp.
Member Function Documentation
const timeval & getMTime () const
Return the last modification timestamp.
Returns:
The last modification timestamp.
Definition at line 72 of file Algorithm.cpp.
References Algorithm::mTime_.
Referenced by ModificationTimeManager::processRequest(), Source::update(), and UppercaseAlgorithm::update().
timeval initMaxTime () [static, private]
Initializes the static constant MAX_TIME.
Returns:
The maximum valid entry in a timeval struct.
Definition at line 30 of file Algorithm.cpp.
References libpipe::utilities::set_max().
timeval initMinTime () [static, private]
Initializes the static constant MIN_TIME.
Returns:
The minimum valid entry in a timeval struct.
Definition at line 39 of file Algorithm.cpp.
References libpipe::utilities::set_min().
bool needUpdate () const
Returns a flag that signifies if the Algorithm needs an update, irrespective of its modification time. The function essentially tests it the modification time of the algorithm is equal to Algorithm::MAX_TIME, signifying that the algorithm needs to be run and that its modification time value should be disregarded. Managers must check needUpdate prior to making use of the information delivered by getMTime. There are two major application scenarios that make use of the flag:
When algorithms are instantiated for the first time, their creation date need not coincide with the execution sequence (this is especially true for filter setups with branches). Hence, their modification time is set to Algorithm::MAX_TIME to guarantee their execution on the first call to update.
When the precursors are deleted the modification time gets set to Algorithm::MIN_TIME to guarantee that the algorithm does not update himself.
Managers in filters that act as sources (i.e. do not have any predecessor) cannot determine the need for execution by comparing Algorithm::getMTime() against their predecessor. In the event that their internal state changes, the manager needs to call this->getAlgorithm()->setMTime(Algorithm::MAX_TIME), thus enforcing an update of the source and propagation along the filter chain.
Returns:
Boolean flag that indicates the need for a call to the algorithm's update function.
Definition at line 88 of file Algorithm.cpp.
References Algorithm::MAX_TIME, and Algorithm::mTime_.
Referenced by ModificationTimeManager::processRequest(), and ROT13Algorithm::update().
void processRequest (libpipe::Request & req)
Processes the current request object. Depending on the information contained in the request object, this will call the update function
Parameters:
[in,out] req A request object.
Definition at line 64 of file Algorithm.cpp.
References Request::is(), Algorithm::MIN_TIME, Algorithm::setMTime(), and Algorithm::update().
Referenced by ModificationTimeManager::processRequest(), and Manager::processRequest().
void setMTime (const timeval & tv)
Set the last modification timestamp.
Parameters:
[in] tv Timestamp.
Definition at line 77 of file Algorithm.cpp.
References Algorithm::mTime_.
Referenced by Algorithm::processRequest(), Source::setParamString(), and Source::Source().
virtual void update (Request & req) [pure virtual]
Runs the algorithm and updates the output data, if the Request Type is Request::Update. If the request Type is Request::DELETE after calling the update function the modification time is fixed to Algorithm::MIN_TIME. Users must overload this method (this is where the beef goes).
Parameters:
[in,out] req The request object (useful for logging/tracing purposes). Also useful to get the type of request (Update of Delete), so that the input can be deleted.
Implemented in Source, UppercaseAlgorithm, LowercaseAlgorithm, CombineAlgorithm, ROT13Algorithm, Source, UppercaseAlgorithm, Source, UppercaseAlgorithm, LowercaseAlgorithm, CombineAlgorithm, ROT13Algorithm, and Source.
Referenced by Algorithm::processRequest().
void updateMTime ()
Update the modification timestamp to the current system time.
Definition at line 82 of file Algorithm.cpp.
References Algorithm::mTime_.
Referenced by UppercaseAlgorithm::setInputString(), Source::update(), and UppercaseAlgorithm::update().
Member Data Documentation
const timeval MAX_TIME [static]
Holds the maximum time value that can be represented in a timeval struct. This is mostly necessary for initialization, but also for the correct behaviour of filters that act as sources.
See also:
updateMTime(), needUpdate()
Definition at line 61 of file Algorithm.hpp.
Referenced by Algorithm::needUpdate(), Source::setParamString(), and Source::Source().
const timeval MIN_TIME [static]
Holds the minimum time value that can be represented in a timeval struct. This is mostly necessary for disconnecting the input filter.
Definition at line 67 of file Algorithm.hpp.
Referenced by Algorithm::processRequest().
timeval mTime_ [private]
The last modification timestamp.
Definition at line 149 of file Algorithm.hpp.
Referenced by Algorithm::getMTime(), Algorithm::needUpdate(), Algorithm::setMTime(), and Algorithm::updateMTime().
The documentation for this class was generated from the following files:
/home/mkirchner/src/libpipe/include/libpipe/ctc/Algorithm.hpp
/home/mkirchner/src/libpipe/src/ctc/Algorithm.cpp