libpipe: PipelineLoader Class Reference
PipelineLoader Class Reference
Code related tolibpipe runtime configuration.
Public Member Functions
PipelineLoader (const std::map< std::string, std::string > &filename)
~PipelineLoader ()
boost::shared_ptr< Filter > getFilter (const std::string &filtername)
const Pipeline & getPipeline () const
Private Types
typedef std::map< std::string,
boost::shared_ptr< Filter > > FilterMap
Private Member Functions
void connectAlgorithmPorts (const std::string &filtername)
void connectManagers (const std::string &filtername)
void generateFilters ()
void generatePipeline ()
Private Attributes
Config * configuration_
FilterMap filterMap_
Pipeline pipeline_
Detailed Description
Generates the objects needed by libpipe, it only relies on the Config interface. And not on the input file.
Definition at line 50 of file PipelineLoader.hpp.
Member Typedef Documentation
typedef std::map<std::string, boost::shared_ptr<Filter> > FilterMap [private]
Typedef of FilterMap
Definition at line 101 of file PipelineLoader.hpp.
Constructor & Destructor Documentation
PipelineLoader (const std::map< std::string, std::string > & filename)
Constructor
Parameters:
filename The names to the configurations file. Identified by a string key.
Definition at line 46 of file PipelineLoader.cpp.
References PipelineLoader::configuration_, PipelineLoader::generateFilters(), PipelineLoader::generatePipeline(), and Config::parseInputFile().
~PipelineLoader ()
Destructor
Definition at line 71 of file PipelineLoader.cpp.
References PipelineLoader::configuration_.
Member Function Documentation
void connectAlgorithmPorts (const std::string & filtername) [private]
This function will connect the ports of the algorithms.
Parameters:
filtername Name of the filter
Definition at line 137 of file PipelineLoader.cpp.
References list< _Tp, _Alloc >::begin(), PipelineLoader::configuration_, list< _Tp, _Alloc >::end(), map< _Key, _Tp, _Compare, _Alloc >::end(), PipelineLoader::filterMap_, map< _Key, _Tp, _Compare, _Alloc >::find(), and Config::getPort().
Referenced by PipelineLoader::generateFilters().
void connectManagers (const std::string & filtername) [private]
This function will connect the managers.
Parameters:
filtername Name of the filter
Definition at line 117 of file PipelineLoader.cpp.
References list< _Tp, _Alloc >::begin(), PipelineLoader::configuration_, list< _Tp, _Alloc >::end(), map< _Key, _Tp, _Compare, _Alloc >::end(), PipelineLoader::filterMap_, map< _Key, _Tp, _Compare, _Alloc >::find(), and Config::getPrecursorFilter().
Referenced by PipelineLoader::generateFilters().
void generateFilters () [private]
This function will generate the filter objects.
Definition at line 95 of file PipelineLoader.cpp.
References list< _Tp, _Alloc >::begin(), map< _Key, _Tp, _Compare, _Alloc >::begin(), PipelineLoader::configuration_, PipelineLoader::connectAlgorithmPorts(), PipelineLoader::connectManagers(), Filter::create(), list< _Tp, _Alloc >::end(), map< _Key, _Tp, _Compare, _Alloc >::end(), PipelineLoader::filterMap_, and Config::getFilters().
Referenced by PipelineLoader::PipelineLoader().
void generatePipeline () [private]
This function will generate the pipeline object
Definition at line 155 of file PipelineLoader.cpp.
References PipelineLoader::configuration_, priority_queue< _Tp, _Sequence, _Compare >::empty(), PipelineDescription::filterName, PipelineLoader::getFilter(), Config::getLibpipePipe(), PipelineDescription::makeTrace, PipelineLoader::pipeline_, priority_queue< _Tp, _Sequence, _Compare >::pop(), Pipeline::push(), PipelineDescription::requestType, Pipeline::setTraceFlag(), and priority_queue< _Tp, _Sequence, _Compare >::top().
Referenced by PipelineLoader::PipelineLoader().
boost::shared_ptr< Filter > getFilter (const std::string & filtername)
Returns a shared pointer to the requested Filter, throws an exception if the filter is not found
Parameters:
filtername The name of the filter one looks for
Returns:
A shared_ptr to a Filter Object
Definition at line 76 of file PipelineLoader.cpp.
References map< _Key, _Tp, _Compare, _Alloc >::end(), PipelineLoader::filterMap_, and map< _Key, _Tp, _Compare, _Alloc >::find().
Referenced by PipelineLoader::generatePipeline().
const Pipeline & getPipeline () const
Returns a LibpipePipeline object, where all information is stored to run libpipe.
Returns:
Reference to a LibpipePipeline.
Definition at line 90 of file PipelineLoader.cpp.
References PipelineLoader::pipeline_.
Member Data Documentation
Config* configuration_ [private]
Pointer to the configuration.
Definition at line 79 of file PipelineLoader.hpp.
Referenced by PipelineLoader::connectAlgorithmPorts(), PipelineLoader::connectManagers(), PipelineLoader::generateFilters(), PipelineLoader::generatePipeline(), PipelineLoader::PipelineLoader(), and PipelineLoader::~PipelineLoader().
FilterMap filterMap_ [private]
Map of the filters identified by their string
Definition at line 105 of file PipelineLoader.hpp.
Referenced by PipelineLoader::connectAlgorithmPorts(), PipelineLoader::connectManagers(), PipelineLoader::generateFilters(), and PipelineLoader::getFilter().
Pipeline pipeline_ [private]
The pipeline object
Definition at line 109 of file PipelineLoader.hpp.
Referenced by PipelineLoader::generatePipeline(), and PipelineLoader::getPipeline().
The documentation for this class was generated from the following files:
/Users/david/Desktop/ETHZ/1_Master/Boston/libpipe/include/libpipe/rtc/PipelineLoader.hpp
/Users/david/Desktop/ETHZ/1_Master/Boston/libpipe/src/rtc/PipelineLoader.cpp