libpipe: libpipe: Filter Class Reference
Filter Class Reference
Code related tolibpipe runtime configuration.
Public Member Functions
~Filter ()
Algorithm * getAlgorithm () const
Manager * getManager () const
std::string getName () const
void processRequest (libpipe::Request &req)
void setName (const std::string &name)
Static Public Member Functions
static Filter * create (const std::string &name, const std::string &algorithmName, const std::string &managerName)
Private Member Functions
Filter (const std::string &name, Algorithm *algorithm, Manager *manager)
void setAlgorithm (Algorithm *alg)
void setManager (Manager *manager)
Private Attributes
Algorithm * algorithm_
boost::shared_mutex algorithmMutex_
Manager * manager_
boost::shared_mutex managerMutex_
std::string name_
boost::shared_mutex nameMutex_
Detailed Description
A filter that supports runtime configuration. Filters are non-copyable composite objects that combine a Manager and an Algorithm object. Note that the Filter destructor is not virtual, that Filter is hence not designed to serve as a base class and that extension of filter functionalities should be implemented by extending its constituents, i.e. Algorithm and Manager.
Definition at line 59 of file Filter.hpp.
Constructor & Destructor Documentation
~Filter ()
Destructor.
Definition at line 52 of file Filter.cpp.
References Filter::algorithm_, Filter::algorithmMutex_, lock(), Filter::manager_, and Filter::managerMutex_.
Filter (const std::string & name, Algorithm * algorithm, Manager * manager) [private]
Constructor.
Parameters:
name The name of the filter.
algorithm Pointer to the Algorithm instance.
manager Pointer to the Manager instance.
Definition at line 47 of file Filter.cpp.
Referenced by Filter::create().
Member Function Documentation
Filter * create (const std::string & name, const std::string & algorithmName, const std::string & managerName) [static]
Filter factory method.
Parameters:
name Unique name of the filter.
algorithmName String that uniquely identifies an algorithm type.
managerName String that uniquely identifies a manager type.
Returns:
A pointer to a new Filter instance.
Definition at line 38 of file Filter.cpp.
References Filter::Filter(), Singleton< T >::instance(), and Manager::setAlgorithm().
Referenced by PipelineLoader::generateFilters().
Algorithm * getAlgorithm () const
Returns a pointer to the algorithm object.
Returns:
A pointer to the algorithm object.
Definition at line 85 of file Filter.cpp.
References Filter::algorithm_, Filter::algorithmMutex_, and lock().
Manager * getManager () const
Returns a pointer to the Manager object.
Returns:
A pointer to the Manager object.
Definition at line 110 of file Filter.cpp.
References lock(), Filter::manager_, and Filter::managerMutex_.
Referenced by Filter::processRequest().
std::string getName () const
Returns the name of the filter.
Returns:
The name of the filter.
Definition at line 131 of file Filter.cpp.
References lock(), Filter::name_, and Filter::nameMutex_.
Referenced by Filter::processRequest().
void processRequest (libpipe::Request & req)
Processes a request. This simply forwards the request to the Algorithm and Manager objects.
Parameters:
[in,out] req The request object.
Definition at line 77 of file Filter.cpp.
References Filter::getManager(), Filter::getName(), and Manager::processRequest().
void setAlgorithm (Algorithm * alg) [private]
Set the algorithm that should be used for this filter.
Parameters:
[in] alg Pointer to the Algorithm object.
Definition at line 93 of file Filter.cpp.
References Filter::algorithm_, Filter::algorithmMutex_, lock(), Filter::manager_, Filter::managerMutex_, and Manager::setAlgorithm().
void setManager (Manager * manager) [private]
Set the manager that manages the filter.
Parameters:
[in] manager Pointer to the Manager object.
Definition at line 118 of file Filter.cpp.
References lock(), Filter::manager_, and Filter::managerMutex_.
void setName (const std::string & name)
Set the name of the filter.
Parameters:
[in] name The name of the filter.
Definition at line 139 of file Filter.cpp.
References lock(), Filter::name_, and Filter::nameMutex_.
Member Data Documentation
Algorithm* algorithm_ [private]
Pointer to the algorithm that is part of the filter.
Definition at line 134 of file Filter.hpp.
Referenced by Filter::getAlgorithm(), Filter::setAlgorithm(), and Filter::~Filter().
boost::shared_mutex algorithmMutex_ [mutable, private]
Mutex for the algorithm_
Definition at line 150 of file Filter.hpp.
Referenced by Filter::getAlgorithm(), Filter::setAlgorithm(), and Filter::~Filter().
Manager* manager_ [private]
Pointer to the manager that is part of the filter.
Definition at line 138 of file Filter.hpp.
Referenced by Filter::getManager(), Filter::setAlgorithm(), Filter::setManager(), and Filter::~Filter().
boost::shared_mutex managerMutex_ [mutable, private]
Mutex for the manager_
Definition at line 154 of file Filter.hpp.
Referenced by Filter::getManager(), Filter::setAlgorithm(), Filter::setManager(), and Filter::~Filter().
std::string name_ [private]
The name of the filter.
Definition at line 142 of file Filter.hpp.
Referenced by Filter::getName(), and Filter::setName().
boost::shared_mutex nameMutex_ [mutable, private]
Mutex for the name_
Definition at line 146 of file Filter.hpp.
Referenced by Filter::getName(), and Filter::setName().
The documentation for this class was generated from the following files:
/home/mkirchner/src/libpipe/include/libpipe/rtc/Filter.hpp
/home/mkirchner/src/libpipe/src/rtc/Filter.cpp