libpipe: libpipe: ConfigJSON Class Reference
ConfigJSON Class Reference
Code related tolibpipe runtime configuration.
Public Member Functions
ConfigJSON ()
~ConfigJSON ()
virtual bool checkFile (const std::map< std::string, std::string > &filename) const
virtual const std::list
< FilterDescription > & getFilters () const
virtual std::priority_queue
< PipelineDescription,
std::vector
< PipelineDescription >
, PipelineDescriptionLess > getLibpipePipe () const
virtual const std::list
< PortDescription > & getPort (const std::string &filtername) const
virtual const std::list
< PrecursorDescription > & getPrecursorFilter (const std::string &filtername) const
virtual void parseInputFile (const std::map< std::string, std::string > &filename)
Private Attributes
std::list< FilterDescription > filterList_
std::priority_queue
< PipelineDescription,
std::vector
< PipelineDescription >
, PipelineDescriptionLess > requestQueue_
Detailed Description
ConfigJSON Class for loading the configuration from JSON files
Definition at line 44 of file ConfigJSON.hpp.
Constructor & Destructor Documentation
ConfigJSON ()
Constructor
Definition at line 43 of file ConfigJSON.cpp.
~ConfigJSON ()
Destructor
Definition at line 47 of file ConfigJSON.cpp.
Member Function Documentation
bool checkFile (const std::map< std::string, std::string > & filename) const [virtual]
Checks the input files. Order is important!
Parameters:
filename Names of the input files
Returns:
true if the file is correct
TODO implement test
Implements Config.
Definition at line 274 of file ConfigJSON.cpp.
const std::list< FilterDescription > & getFilters () const [virtual]
Gives a list of all Filters that need to be generated
Returns:
A list of Filters
Implements Config.
Definition at line 52 of file ConfigJSON.cpp.
References ConfigJSON::filterList_.
std::priority_queue< PipelineDescription, std::vector< PipelineDescription >, PipelineDescriptionLess > getLibpipePipe () const [virtual]
Returns the libpipe Pipeline
Returns:
A priority_queue where all elements are ordered after their request rank, the smallest comes first
Implements Config.
Definition at line 93 of file ConfigJSON.cpp.
References ConfigJSON::requestQueue_.
const std::list< PortDescription > & getPort (const std::string & filtername) const [virtual]
Returns the ports
Parameters:
filtername The name of the Filter which ports are returned
Returns:
list of all ports one Filter is connected to
Implements Config.
Definition at line 75 of file ConfigJSON.cpp.
References list< _Tp, _Alloc >::begin(), list< _Tp, _Alloc >::end(), and ConfigJSON::filterList_.
const std::list< PrecursorDescription > & getPrecursorFilter (const std::string & filtername) const [virtual]
Returns the precursor Filters
Parameters:
filtername The name of the Filter, which manager get connected to the Precursors
Returns:
List of Precursors Filter filtername gets connected to
Implements Config.
Definition at line 57 of file ConfigJSON.cpp.
References list< _Tp, _Alloc >::begin(), list< _Tp, _Alloc >::end(), and ConfigJSON::filterList_.
void parseInputFile (const std::map< std::string, std::string > & filename) [virtual]
Parses the input files.
key: "FilterInput" Input file with the Filter Configuration
key: "ConnectionInput" Input file with the Connection Configurations
key: "PipelineInput" Input file with the Pipeline configuration
Parameters:
filename Names of the input files
Implements Config.
Definition at line 98 of file ConfigJSON.cpp.
References Parameters::addRequiredParameters(), FilterDescription::algorithmName, list< _Tp, _Alloc >::begin(), list< _Tp, _Alloc >::end(), ConfigJSON::filterList_, PipelineDescription::filterName, PortDescription::filterName, FilterDescription::filterName, map< _Key, _Tp, _Compare, _Alloc >::find(), PipelineDescription::makeTrace, FilterDescription::managerName, PortDescription::portNameOfFilter, PortDescription::portNameOfThis, FilterDescription::ports, PrecursorDescription::precursorName, FilterDescription::precursors, priority_queue< _Tp, _Sequence, _Compare >::push(), vector< _Tp, _Alloc >::push_back(), list< _Tp, _Alloc >::push_back(), ConfigJSON::requestQueue_, PipelineDescription::requestRank, PipelineDescription::requestType, Parameters::set(), and exception::what().
Member Data Documentation
std::list<FilterDescription> filterList_ [private]
List of Filters descriptions
Definition at line 102 of file ConfigJSON.hpp.
Referenced by ConfigJSON::getFilters(), ConfigJSON::getPort(), ConfigJSON::getPrecursorFilter(), and ConfigJSON::parseInputFile().
std::priority_queue<PipelineDescription, std::vector<PipelineDescription>, PipelineDescriptionLess> requestQueue_ [private]
Pipeline of request informations
Definition at line 106 of file ConfigJSON.hpp.
Referenced by ConfigJSON::getLibpipePipe(), and ConfigJSON::parseInputFile().
The documentation for this class was generated from the following files:
/home/mkirchner/src/libpipe/include/libpipe/rtc/ConfigJSON.hpp
/home/mkirchner/src/libpipe/src/rtc/ConfigJSON.cpp