libpipe: ModificationTimeManager Class Reference
ModificationTimeManager Class Reference
Code related to the compile-time configuration
Public Member Functions
ModificationTimeManager ()
virtual ~ModificationTimeManager ()
void connect (boost::shared_ptr< Filter > f)
Algorithm * getAlgorithm ()
virtual void processRequest (libpipe::Request &req)
void setAlgorithm (Algorithm *alg)
Protected Types
typedef std::set
< boost::shared_ptr< Filter > > FilterSet
Protected Member Functions
void disconnect ()
Protected Attributes
Algorithm * algorithm_
FilterSet sources_
Detailed Description
A manager class that makes use of the modification time information of the algoritms it manages.
Definition at line 41 of file ModificationTimeManager.hpp.
Member Typedef Documentation
typedef std::set<boost::shared_ptr<Filter> > FilterSet [protected, inherited]
Convenience typedef: a filter set.
Definition at line 100 of file Manager.hpp.
Constructor & Destructor Documentation
ModificationTimeManager ()
Constructor.
Definition at line 34 of file ModificationTimeManager.cpp.
~ModificationTimeManager () [virtual]
Destructor. Virtual, to allow subclassing.
Definition at line 39 of file ModificationTimeManager.cpp.
Member Function Documentation
void connect (boost::shared_ptr< Filter > f) [inherited]
Connect the manager to a filter it depends on. Each call connects the Manager to the specified filter; duplicates will be ignored. Because of the use of shared_pointers one need to dynamically cast the pointers to boost::shared_ptr<Filter> this can be done with the use of boost::dynamic_pointer_cast<Filter>
 ...
 boost::shared_ptr<UserFilter> uf (new UserFilter("FilterName"));
 ...
 uf->getManager()->connect(boost::dynamic_pointer_cast<Filter>(someOtherFilter->getManager()));
Parameters:
[in,out] f Pointer to a filter object on which the current manager should depend.
Definition at line 84 of file Manager.cpp.
References set< _Key, _Compare, _Alloc >::insert(), and Manager::sources_.
void disconnect () [protected, inherited]
Disconnects the manager from all his input filters. The Algorithm calls does at the same time fix the output of the corresponding Algorithm, so that the output will stay constant.
Definition at line 89 of file Manager.cpp.
References set< _Key, _Compare, _Alloc >::clear(), and Manager::sources_.
Referenced by Manager::processRequest().
Algorithm * getAlgorithm () [inherited]
Get a pointer to the algorithm object currently managed by the manager.
Returns:
A pointer to an algorithm object (or 0).
Definition at line 39 of file Manager.cpp.
References Manager::algorithm_.
void processRequest (libpipe::Request & req) [virtual]
Processes a request, taking into account the current modification time of the Manager's algorithm.
Parameters:
[in,out] req The request object.
Reimplemented from Manager.
Definition at line 43 of file ModificationTimeManager.cpp.
References Manager::algorithm_, set< _Key, _Compare, _Alloc >::begin(), set< _Key, _Compare, _Alloc >::end(), Algorithm::getMTime(), Algorithm::needUpdate(), Algorithm::processRequest(), Manager::sources_, and exception::what().
void setAlgorithm (Algorithm * alg) [inherited]
Set the algorithm that is managed by the manager.
Parameters:
[in] alg Pointer to the algorithm object.
Definition at line 44 of file Manager.cpp.
References Manager::algorithm_.
Referenced by Filter::setAlgorithm().
Member Data Documentation
Algorithm* algorithm_ [protected, inherited]
Pointer to the algorithm that is managed by the manager.
Definition at line 108 of file Manager.hpp.
Referenced by Manager::getAlgorithm(), ModificationTimeManager::processRequest(), Manager::processRequest(), and Manager::setAlgorithm().
FilterSet sources_ [protected, inherited]
The set of filters the manager depends on.
Definition at line 104 of file Manager.hpp.
Referenced by Manager::connect(), Manager::disconnect(), ModificationTimeManager::processRequest(), and Manager::processRequest().
The documentation for this class was generated from the following files:
/Users/david/Desktop/ETHZ/1_Master/Boston/libpipe/include/libpipe/ctc/ModificationTimeManager.hpp
/Users/david/Desktop/ETHZ/1_Master/Boston/libpipe/src/ctc/ModificationTimeManager.cpp