libpipe: ROT13Algorithm Class Reference
ROT13Algorithm Class Reference
Public Types
typedef
libpipe::rtc::SharedData
< String > SharedString
typedef std::string String
Public Member Functions
ROT13Algorithm ()
virtual ~ROT13Algorithm ()
virtual ~ROT13Algorithm ()
void connect (Algorithm *alg, const std::string &algPortIdentifier, const std::string &thisPortIdentifier)
const timeval & getMTime () const
const timeval & getMTime () const
boost::shared_ptr
< libpipe::ctc::SharedData
< std::string > > getOutput ()
boost::shared_ptr< Data > getPort (const std::string &portIdentifier) const
bool needUpdate () const
bool needUpdate () const
void processRequest (Request &req)
void processRequest (Request &req)
void setInput (boost::shared_ptr< libpipe::ctc::SharedData< std::string > > input)
void setMTime (const timeval &tv)
void setMTime (const timeval &tv)
void setParameters (const libpipe::utilities::Parameters &param)
void setPort (const std::string &portIdentifier, boost::shared_ptr< Data > dataObject)
void update (libpipe::Request &req)
void update (libpipe::Request &req)
void updateMTime ()
void updateMTime ()
Static Public Member Functions
static Algorithm * create ()
Static Public Attributes
static const timeval MAX_TIME
static const timeval MAX_TIME
static const timeval MIN_TIME
static const timeval MIN_TIME
Protected Types
typedef boost::shared_ptr
< libpipe::ctc::SharedData
< std::string > > StringPtr
Protected Attributes
StringPtr input_
StringPtr output_
libpipe::utilities::Parameters parameters_
std::map< std::string,
boost::shared_ptr< Data > > ports_
Private Member Functions
ROT13Algorithm ()
void rot13 (const String &str, String &result)
void rot13 (boost::shared_ptr< libpipe::ctc::SharedData< std::string > > str, boost::shared_ptr< libpipe::ctc::SharedData< std::string > > result)
Static Private Member Functions
static const bool registerLoader ()
Static Private Attributes
static const bool registered_
Detailed Description
cipher the string with ROT13
Definition at line 324 of file example-rtc.cpp.
Member Typedef Documentation
typedef boost::shared_ptr<libpipe::ctc::SharedData<std::string> > StringPtr [protected]
Typedef of input pointers
Definition at line 444 of file example-uppercase-strings.cpp.
Constructor & Destructor Documentation
virtual ~ROT13Algorithm () [virtual]
virtual Destructor
Definition at line 338 of file example-rtc.cpp.
ROT13Algorithm () [private]
Constructor. Make sure to call the libpipe::Algorithm constructor.
Definition at line 409 of file example-rtc.cpp.
References Algorithm::ports_.
Referenced by create().
ROT13Algorithm ()
Constructor. Make sure to call the libpipe::Algorithm constructor.
Definition at line 370 of file example-uppercase-strings.cpp.
virtual ~ROT13Algorithm () [virtual]
virtual Destructor
Definition at line 379 of file example-uppercase-strings.cpp.
References std::cout, std::endl(), input_, and output_.
Member Function Documentation
void connect (Algorithm * alg, const std::string & algPortIdentifier, const std::string & thisPortIdentifier) [inherited]
Connects the port of this algorithm identified by thisPortIdentifier to the port of alg algorithm identified by algPortIdentifier
Parameters:
alg Algorithm which port is connected to the port of this algorithm
algPortIdentifier Identifier of the port of alg
thisPortIdentifier Identifier of the port of this algorithm
Definition at line 161 of file Algorithm.cpp.
References Algorithm::getPort(), and Algorithm::setPort().
static Algorithm* create () [static]
create Static constructor. A pointer to this function along with the name of the algorithm is registered with the Algorithm Factory.
Returns:
Pointer to a new Algorithm instance. Responsibility for allocated memory lies with the caller.
Reimplemented from Algorithm.
Definition at line 331 of file example-rtc.cpp.
References ROT13Algorithm().
Referenced by registerLoader().
const timeval & getMTime () const [inherited]
Return the last modification timestamp.
Returns:
The last modification timestamp.
Definition at line 72 of file Algorithm.cpp.
References Algorithm::mTime_.
Referenced by ModificationTimeManager::processRequest(), UppercaseAlgorithm::update(), and Source::update().
const timeval & getMTime () const [inherited]
Return the last modification timestamp.
Returns:
The last modification timestamp.
Definition at line 84 of file Algorithm.cpp.
References lock(), and Algorithm::mTime_.
boost::shared_ptr<libpipe::ctc::SharedData<std::string> > getOutput ()
Provides access to results. In contrast to more rigid pipeline implementations, LIBPIPE does not impose any constraints on what data types algorithms can share; this is simply done by keeping the request pipeline separate from the input/output flow of the algorithms. In most cases the user knows best which data type is suitable for a problem at hand; there is no reason to take this freedom (and the responsibility from her/him. Algorithms need to specify input and output functions, and it is recommended (but not required) to start the respective function names with 'setInput' and 'getOutput'.
Returns:
A handle to the output data of the algorithm.
Definition at line 425 of file example-uppercase-strings.cpp.
References output_.
boost::shared_ptr< Data > getPort (const std::string & portIdentifier) const [inherited]
Returns a base class pointer to the data object located at the specified port.
Note:
To actually use the object, it is necessary to caryy out a make dynamic pointer cast to the actual object type, e.g.
 // assuming (*this) is a filter object
 boost::shared_ptr<Data> port = this->getPort("MyStringInput");
 typedef libpipe::rtc::SharedData<std::string> SharedString;
 SharedString sharedStr = boost::dynamic_pointer_cast<SharedString>(port);
 const std::string& str = *(sharedStr->get())
 // ...
Parameters:
portIdentifier A std::string which identifies the port one wants to use
Returns:
A shared_ptr to a LibpipeDataObject
Definition at line 122 of file Algorithm.cpp.
References map< _Key, _Tp, _Compare, _Alloc >::end(), map< _Key, _Tp, _Compare, _Alloc >::find(), lock(), and Algorithm::ports_.
Referenced by Algorithm::connect().
bool needUpdate () const [inherited]
Returns a flag that signifies if the Algorithm needs an update, irrespective of its modification time. The function essentially tests it the modification time of the algorithm is equal to Algorithm::MAX_TIME, signifying that the algorithm needs to be run and that its modification time value should be disregarded. Managers must check needUpdate prior to making use of the information delivered by getMTime. There are two major application scenarios that make use of the flag:
When algorithms are instantiated for the first time, their creation date need not coincide with the execution sequence (this is especially true for filter setups with branches). Hence, their modification time is set to Algorithm::MAX_TIME to guarantee their execution on the first call to update.
When the precursors are deleted the modification time gets set to Algorithm::MIN_TIME to guarantee that the algorithm does not update himself.
Managers in filters that act as sources (i.e. do not have any predecessor) cannot determine the need for execution by comparing Algorithm::getMTime() against their predecessor. In the event that their internal state changes, the manager needs to call this->getAlgorithm()->setMTime(Algorithm::MAX_TIME), thus enforcing an update of the source and propagation along the filter chain.
Returns:
Boolean flag that indicates the need for a call to the algorithm's update function.
Definition at line 88 of file Algorithm.cpp.
References Algorithm::MAX_TIME, and Algorithm::mTime_.
Referenced by ModificationTimeManager::processRequest(), and update().
bool needUpdate () const [inherited]
Returns a flag that signifies if the Algorithm needs an update, irrespective of its modification time. The function essentially tests it the modification time of the algorithm is equal to Algorithm::MAX_TIME, signifying that the algorithm needs to be run and that its modification time value should be disregarded. Managers must check needUpdate prior to making use of the information delivered by getMTime. There are three major application scenarios that make use of the flag:
When algorithms are instantiated for the first time, their creation date need not coincide with the execution sequence (this is especially true for filter setups with branches). Hence, their modification time is set to Algorithm::MAX_TIME to guarantee their execution on the first call to update.
When the precursors are deleted the modification time gets set to Algorithm::MIN_TIME to guarantee that the algorithm does not update himself.
Managers in filters that act as sources (i.e. do not have any predecessor) cannot determine the need for execution by comparing Algorithm::getMTime() against their predecessor. In the event that their internal state changes, the manager needs to call this->getAlgorithm()->setMTime(Algorithm::MAX_TIME), thus enforcing an update of the source and propagation along the filter chain.
Returns:
Boolean flag that indicates the need for a call to the algorithm's update function.
Definition at line 114 of file Algorithm.cpp.
References lock(), Algorithm::MAX_TIME, and Algorithm::mTime_.
void processRequest (libpipe::Request & req) [inherited]
Processes the current request object. Depending on the information contained in the request object, this will call the update function
Parameters:
[in,out] req A request object.
Definition at line 64 of file Algorithm.cpp.
References Request::is(), Algorithm::MIN_TIME, Algorithm::setMTime(), and Algorithm::update().
Referenced by ModificationTimeManager::processRequest(), and Manager::processRequest().
void processRequest (libpipe::Request & req) [inherited]
Processes the current request object. In most implementations, this will simply forward the request object to the update function.
Parameters:
[in,out] req A request object.
Definition at line 72 of file Algorithm.cpp.
References Request::is(), lock(), Algorithm::MIN_TIME, Algorithm::setMTime(), and Algorithm::update().
Referenced by Manager::processRequest().
static const bool registerLoader () [static, private]
registers the Algorithm in the factory
Returns:
true is registration was successful
Definition at line 419 of file example-rtc.cpp.
References create(), and Singleton< T >::instance().
void rot13 (const String & str, String & result) [private]
Function to calculate the ROT13 cipher
Parameters:
[in] str A handle to the input string
[out] result A handle to the ciphered input
Definition at line 386 of file example-rtc.cpp.
References basic_string< _CharT, _Traits, _Alloc >::reserve().
Referenced by update().
void rot13 (boost::shared_ptr< libpipe::ctc::SharedData< std::string > > str, boost::shared_ptr< libpipe::ctc::SharedData< std::string > > result) [private]
Function to calculate the ROT13 cipher
Parameters:
[in] str A handle to the input string
[out] result A handle to the ciphered input
Definition at line 465 of file example-uppercase-strings.cpp.
References basic_string< _CharT, _Traits, _Alloc >::reserve().
void setInput (boost::shared_ptr< libpipe::ctc::SharedData< std::string > > input)
Allows to connect the output of another algorithm with the input of this algorithm.
See also:
getOutput
Parameters:
[in] input A handle (in most cases a (smart) pointer to the data.)
Definition at line 436 of file example-uppercase-strings.cpp.
References input_.
void setMTime (const timeval & tv) [inherited]
Set the last modification timestamp.
Parameters:
[in] tv Timestamp.
Definition at line 77 of file Algorithm.cpp.
References Algorithm::mTime_.
Referenced by Algorithm::processRequest(), Source::setParamString(), and Source::Source().
void setMTime (const timeval & tv) [inherited]
Set the last modification timestamp.
Parameters:
[in] tv Timestamp.
Definition at line 92 of file Algorithm.cpp.
References lock(), and Algorithm::mTime_.
Referenced by Algorithm::processRequest().
void setParameters (const libpipe::utilities::Parameters & param) [inherited]
Set the parameters
Parameters:
param The Parameters where paramters are set to.
Definition at line 100 of file Algorithm.cpp.
References Algorithm::parameters_.
void setPort (const std::string & portIdentifier, boost::shared_ptr< Data > dataObject) [inherited]
Sets the Port to a certain LibpipeDataObject
Parameters:
portIdentifier A std::string which identifies the port one wants to set to the LibpipeDataObject dataObject
dataObject The Object the Port will point to
Definition at line 142 of file Algorithm.cpp.
References map< _Key, _Tp, _Compare, _Alloc >::end(), map< _Key, _Tp, _Compare, _Alloc >::find(), lock(), and Algorithm::ports_.
Referenced by Algorithm::connect().
void update (libpipe::Request & req) [virtual]
Runs the algorithm and updates the output data. If the request type is DELETE the input gets deleted. This is where all the algorithm implementation goes.
Parameters:
[in,out] req The request object, forwarded from process request.
Returns:
The request
Implements Algorithm.
Definition at line 349 of file example-rtc.cpp.
References input_, Request::is(), Algorithm::needUpdate(), output_, and rot13().
void update (libpipe::Request & req) [virtual]
Runs the algorithm and updates the output data. If the request type is DELETE the input gets deleted. This is where all the algorithm implementation goes.
Parameters:
[in,out] req The request object, forwarded from process request.
Returns:
the Request
Implements Algorithm.
Definition at line 397 of file example-uppercase-strings.cpp.
References input_, Request::is(), Algorithm::needUpdate(), output_, and rot13().
void updateMTime () [inherited]
Update the modification timestamp to the current system time.
Definition at line 82 of file Algorithm.cpp.
References Algorithm::mTime_.
Referenced by UppercaseAlgorithm::setInputString(), UppercaseAlgorithm::update(), and Source::update().
void updateMTime () [inherited]
Update the modification timestamp to the current system time.
Definition at line 105 of file Algorithm.cpp.
References lock(), and Algorithm::mTime_.
Member Data Documentation
StringPtr input_ [protected]
A reference to the input data. This can be a weak pointer or some other kind of reference. In the majority of cases, the algorithm should not attempt to modify this data. There are exceptions (and hence constness is not enforced).
Definition at line 456 of file example-uppercase-strings.cpp.
Referenced by setInput(), update(), and ~ROT13Algorithm().
const timeval MAX_TIME [static, inherited]
Holds the maximum time value that can be represented in a timeval struct. This is mostly necessary for initialization, but also for the correct behaviour of filters that act as sources.
See also:
updateMTime(), needUpdate()
Definition at line 61 of file Algorithm.hpp.
Referenced by Algorithm::needUpdate(), Source::setParamString(), and Source::Source().
const timeval MAX_TIME [static, inherited]
Holds the maximum time value that can be represented in a timeval struct. This is necessary for initialization and for the correct behaviour of filters that act as sources.
See also:
updateMTime(), needUpdate()
Definition at line 78 of file Algorithm.hpp.
Referenced by Algorithm::needUpdate().
const timeval MIN_TIME [static, inherited]
Holds the minimum time value that can be represented in a timeval struct. This is mostly necessary for disconnecting the input filter.
Definition at line 67 of file Algorithm.hpp.
Referenced by Algorithm::processRequest().
const timeval MIN_TIME [static, inherited]
Holds the minimum time value that can be represented in a timeval struct. This is necessary when disconnecting filter inputs.
Definition at line 83 of file Algorithm.hpp.
Referenced by Algorithm::processRequest().
StringPtr output_ [protected]
The output data. In most cases it is advisable that the memory consumed by this data is owned by the algorithm (or, at least, managed by it).
Definition at line 449 of file example-uppercase-strings.cpp.
Referenced by getOutput(), update(), and ~ROT13Algorithm().
libpipe::utilities::Parameters parameters_ [protected, inherited]
Stores the parameters needed by the update methode of the algorithm
Definition at line 204 of file Algorithm.hpp.
Referenced by Algorithm::setParameters(), and Source::update().
std::map<std::string, boost::shared_ptr<Data> > ports_ [protected, inherited]
Map of the ports and their std::string Identifier
Definition at line 200 of file Algorithm.hpp.
Referenced by CombineAlgorithm::CombineAlgorithm(), Algorithm::getPort(), LowercaseAlgorithm::LowercaseAlgorithm(), MatrixMulAlgorithm::MatrixMulAlgorithm(), Printer::Printer(), ROT13Algorithm(), Algorithm::setPort(), Source::Source(), and UppercaseAlgorithm::UppercaseAlgorithm().
const bool registered_ [static, private]
true is class is registered in Algorithm Factory
Definition at line 426 of file example-rtc.cpp.
The documentation for this class was generated from the following files:
/Users/david/Desktop/ETHZ/1_Master/Boston/libpipe/examples/example-rtc.cpp
/Users/david/Desktop/ETHZ/1_Master/Boston/libpipe/examples/example-uppercase-strings.cpp