libpipe: Config Class Reference
Config Class Reference
Code related tolibpipe runtime configuration.
Public Member Functions
virtual ~Config ()=0
virtual bool checkFile (const std::map< std::string, std::string > &filename) const =0
virtual const std::list
< FilterDescription > & getFilters () const =0
virtual std::priority_queue
< PipelineDescription,
std::vector
< PipelineDescription >
, PipelineDescriptionLess > getLibpipePipe () const =0
virtual const std::list
< PortDescription > & getPort (const std::string &filtername) const =0
virtual const std::list
< PrecursorDescription > & getPrecursorFilter (const std::string &filtername) const =0
virtual void parseInputFile (const std::map< std::string, std::string > &filename)=0
Detailed Description
Interface for all Classes which loads configuration files.
Definition at line 135 of file Config.hpp.
Constructor & Destructor Documentation
~Config () [pure virtual]
Virtual Destructor to allow inheritance.
Definition at line 33 of file Config.cpp.
Member Function Documentation
virtual bool checkFile (const std::map< std::string, std::string > & filename) const [pure virtual]
Checks the input files. Order is important!
Parameters:
filename Names of the input files. Identified by a string key.
Returns:
true if the file is ok
Implemented in ConfigJSON.
virtual const std::list<FilterDescription>& getFilters () const [pure virtual]
Gives a list of all Filters that need to be generated
Returns:
A list of Filters
Implemented in ConfigJSON.
Referenced by PipelineLoader::generateFilters().
virtual std::priority_queue<PipelineDescription, std::vector<PipelineDescription>, PipelineDescriptionLess> getLibpipePipe () const [pure virtual]
Returns:
A priority_queue where all elements are ordered after their request rank, the smallest comes first
Implemented in ConfigJSON.
Referenced by PipelineLoader::generatePipeline().
virtual const std::list<PortDescription>& getPort (const std::string & filtername) const [pure virtual]
Parameters:
filtername The name of the Filter which ports are returned
Returns:
list of all ports one Filter is connected to
Implemented in ConfigJSON.
Referenced by PipelineLoader::connectAlgorithmPorts().
virtual const std::list<PrecursorDescription>& getPrecursorFilter (const std::string & filtername) const [pure virtual]
Parameters:
filtername The name of the Filter, which manager get connected to the Precursors
Returns:
List of Precursors Filter filtername gets connected to
Implemented in ConfigJSON.
Referenced by PipelineLoader::connectManagers().
virtual void parseInputFile (const std::map< std::string, std::string > & filename) [pure virtual]
Parses the input files. Order is important!
Parameters:
filename Names of the input files. Identifed by a string key
Implemented in ConfigJSON.
Referenced by PipelineLoader::PipelineLoader().
The documentation for this class was generated from the following files:
/Users/david/Desktop/ETHZ/1_Master/Boston/libpipe/include/libpipe/rtc/Config.hpp
/Users/david/Desktop/ETHZ/1_Master/Boston/libpipe/src/rtc/Config.cpp