libpipe: Singleton< T > Class Template Reference
Singleton< T > Class Template Reference
Public Member Functions
~Singleton ()
Static Public Member Functions
static T & instance ()
Private Member Functions
Singleton ()
Singleton (const Singleton &S)
Singleton & operator= (const Singleton &S)
Static Private Member Functions
static void create ()
Static Private Attributes
static bool destroyed_
static T * pInstance_
Detailed Description
template<class T>
class libpipe::utilities::Singleton< T >
Singleton holder template class. Template class to create singletons. A singleton instance of class MyType is created and accessed using
 typedef Singleton<MyType> MySingletonType;
 MyType& myRef = MySingletonType::instance()
 // ... do something ...
Definition at line 46 of file Singleton.hpp.
Constructor & Destructor Documentation
~Singleton ()
Destructor.
Definition at line 114 of file Singleton.hpp.
Singleton () [private]
Private constructor to disallow explicit construction. Is not defined.
Singleton (const Singleton< T > & S) [private]
Private copy constructor to disallow explicit copying. Is not defined.
Parameters:
S A singleton object.
Member Function Documentation
void create () [static, private]
Create method. Creates the singleton instance (a Meyers singleton, ie. a function static object) upon the first call to instance().
Definition at line 120 of file Singleton.hpp.
T & instance () [static]
Return a reference to the only instance of Singleton<T>.
Returns:
A reference to the instance of the object.
Returns the unique instance of class T. If it was already deleted an exception is thrown. If the class T was never used before a new instance is generated.
Returns:
Unique instance of class T
Definition at line 100 of file Singleton.hpp.
Referenced by Filter::create(), UppercaseAlgorithm::registerLoader(), MatrixMulAlgorithm::registerLoader(), Manager::registerLoader(), Source::registerLoader(), LowercaseAlgorithm::registerLoader(), Printer::registerLoader(), Handler::registerLoader(), CombineAlgorithm::registerLoader(), and ROT13Algorithm::registerLoader().
Singleton& operator= (const Singleton< T > & S) [private]
Provate assignment operator to disallow explicit assignment. Is not defined.
Parameters:
S A singleton object.
Returns:
The current singleton.
Member Data Documentation
bool destroyed_ [static, private]
Status of the singleton. True if the singleton was destroyed.
Definition at line 90 of file Singleton.hpp.
T * pInstance_ [static, private]
Pointer to the instance.
Definition at line 86 of file Singleton.hpp.
The documentation for this class was generated from the following file:
/Users/david/Desktop/ETHZ/1_Master/Boston/libpipe/include/libpipe/utilities/Singleton.hpp