libpipe: Manager Class Reference
Manager Class Reference
Code related tolibpipe runtime configuration.
Public Member Functions
virtual ~Manager ()
void connect (boost::shared_ptr< Filter > f)
Algorithm * getAlgorithm ()
virtual void processRequest (libpipe::Request &req)
void setAlgorithm (Algorithm *alg)
Static Public Member Functions
static Manager * create ()
Protected Types
typedef std::set
< boost::shared_ptr< Filter > > FilterSet
Protected Member Functions
Manager ()
void disconnect ()
Protected Attributes
Algorithm * algorithm_
FilterSet sources_
Private Member Functions
std::set< boost::shared_ptr
< Filter > > getSources ()
Static Private Member Functions
static const bool registerLoader ()
Static Private Attributes
static const bool registered_
Detailed Description
Base class for runtime configuration Managers. Managers are wrapped with Algorithms to form the filters of the pipeline. While the filters provide all data processing capabilities, the managers link the components of the pipeline and make sure that filters get executed in the correct order.
Definition at line 56 of file Manager.hpp.
Member Typedef Documentation
typedef std::set<boost::shared_ptr<Filter> > FilterSet [protected]
Convenience typedef: a filter set.
Definition at line 115 of file Manager.hpp.
Constructor & Destructor Documentation
~Manager () [virtual]
Destructor.
Definition at line 46 of file Manager.cpp.
Manager () [protected]
Constructor.
Definition at line 41 of file Manager.cpp.
Referenced by Manager::create().
Member Function Documentation
void connect (boost::shared_ptr< Filter > f)
Construct dependencies between filters. Each call connects the Manager to the specified filter; duplicates will be ignored. Because of the use of shared_pointers one need to dynamically cast the pointers to boost::shared_ptr<Filter> this can be done with the use of boost::dynamic_pointer_cast<Filter>
 ...
 boost::shared_ptr<UserFilter> uf (new UserFilter("FilterName"));
 ...
 uf->getManager()->connect(boost::dynamic_pointer_cast<Filter>(someOtherFilter->getManager()));
Parameters:
[in,out] f Pointer to a filter object on which the current manager should depend.
Definition at line 137 of file Manager.cpp.
References set< _Key, _Compare, _Alloc >::insert(), lock(), and Manager::sources_.
Manager * create () [static]
Factory method for Manager objects. Call
Returns:
A Pointer to a new Manager object. Ownership lies with the caller.
Definition at line 36 of file Manager.cpp.
References Manager::Manager().
Referenced by Manager::registerLoader().
void disconnect () [protected]
Disconnects the manager from all his input filters. The Algorithm calls does at the same time fix the output of the corresponding Algorithm, so that the output will stay constant.
Definition at line 145 of file Manager.cpp.
References set< _Key, _Compare, _Alloc >::clear(), lock(), and Manager::sources_.
Referenced by Manager::processRequest().
Algorithm * getAlgorithm ()
Get a pointer to the Algorithm object that is currently managed by the manager.
Returns:
Pointer to an Algorithm object (or 0).
Definition at line 50 of file Manager.cpp.
References Manager::algorithm_, and lock().
std::set< boost::shared_ptr< Filter > > getSources () [private]
Returns the Filter Manager is dependent on
Returns:
A Set of shared_ptr to Filters
Definition at line 153 of file Manager.cpp.
References lock(), and Manager::sources_.
void processRequest (libpipe::Request & req) [virtual]
Process a request. In the default base class implementation, the manager calls the processRequest methods of all filters it depends. It subsequently executes Algorithm::processRequest on its own Algorithm instance.
Parameters:
[in,out] req The request object, non-const (good for e.g. adding trace information)
Definition at line 68 of file Manager.cpp.
References Manager::algorithm_, vector< _Tp, _Alloc >::begin(), set< _Key, _Compare, _Alloc >::begin(), Manager::disconnect(), set< _Key, _Compare, _Alloc >::end(), Request::is(), lock(), Algorithm::processRequest(), rethrow_exception(), set< _Key, _Compare, _Alloc >::size(), Manager::sources_, exception::what(), and Exception::what().
Referenced by Filter::processRequest().
const bool registerLoader () [static, private]
Registers the manager in the managerfactory
Returns:
true if successful
Definition at line 161 of file Manager.cpp.
References Manager::create(), and Singleton< T >::instance().
void setAlgorithm (Algorithm * alg)
Set the Algorithm object that is managed by the manager.
Parameters:
[in] alg Pointer to the algorithm object.
Definition at line 58 of file Manager.cpp.
References Manager::algorithm_, and lock().
Referenced by Filter::create(), and Filter::setAlgorithm().
Member Data Documentation
Algorithm* algorithm_ [protected]
Pointer to the algorithm that is managed by the manager.
Definition at line 123 of file Manager.hpp.
Referenced by Manager::getAlgorithm(), Manager::processRequest(), and Manager::setAlgorithm().
const bool registered_ [static, private]
Register Filter in the FilterFactory
Definition at line 141 of file Manager.hpp.
FilterSet sources_ [protected]
The set of filters the manager depends on.
Definition at line 119 of file Manager.hpp.
Referenced by Manager::connect(), Manager::disconnect(), Manager::getSources(), and Manager::processRequest().
The documentation for this class was generated from the following files:
/Users/david/Desktop/ETHZ/1_Master/Boston/libpipe/include/libpipe/rtc/Manager.hpp
/Users/david/Desktop/ETHZ/1_Master/Boston/libpipe/src/rtc/Manager.cpp