libpipe: Request Class Reference
Request Class Reference
Public Types
enum Type { UPDATE, DELETE }
Public Member Functions
Request (const Type &t)
Request ()
virtual ~Request ()
Type getType () const
bool is (const Type &t)
Protected Attributes
Type type_
Detailed Description
A request object. The request object is used to transfer requests between filters.
Definition at line 39 of file Request.hpp.
Member Enumeration Documentation
enum Type
Defines the request type. UPDATE for updating the filters DELETE for deleting the filters
Definition at line 46 of file Request.hpp.
Constructor & Destructor Documentation
Request (const Type & t)
Constructor. Requires a request type.
Parameters:
[in] t The type of the request.
Definition at line 32 of file Request.cpp.
Request ()
Constructor Type is Update
Definition at line 37 of file Request.cpp.
~Request () [virtual]
Destructor. Virtual, to allow subclassing.
Definition at line 42 of file Request.cpp.
Member Function Documentation
Request::Type getType () const
Returns the type of request
Returns:
The Request Type of the request
Definition at line 51 of file Request.cpp.
References Request::type_.
Referenced by Pipeline::run().
bool is (const Type & t)
Tests the type of a request.
Parameters:
[in] t A request type.
Returns:
true of t is of the same type as this
Definition at line 46 of file Request.cpp.
References Request::type_.
Referenced by Manager::processRequest(), Algorithm::processRequest(), and ROT13Algorithm::update().
Member Data Documentation
Type type_ [protected]
The request type.
See also:
Type
Definition at line 83 of file Request.hpp.
Referenced by Request::getType(), and Request::is().
The documentation for this class was generated from the following files:
/Users/david/Desktop/ETHZ/1_Master/Boston/libpipe/include/libpipe/Request.hpp
/Users/david/Desktop/ETHZ/1_Master/Boston/libpipe/src/Request.cpp