libpipe: Filter Class Reference
Filter Class Reference
Code related to the compile-time configuration
Public Member Functions
Filter (const std::string &)
virtual ~Filter ()
virtual Algorithm * getAlgorithm ()
virtual Manager * getManager ()
std::string getName () const
virtual void processRequest (libpipe::Request &req)
void setName (const std::string &name)
Protected Member Functions
void setAlgorithm (Algorithm *alg)
void setManager (Manager *manager)
Private Attributes
Algorithm * algorithm_
Manager * manager_
std::string name_
Detailed Description
The base class for all LIBPIPE filters. Filters are non-copyable by default.
Definition at line 47 of file Filter.hpp.
Constructor & Destructor Documentation
Filter (const std::string & name)
Constructor.
Definition at line 33 of file Filter.cpp.
~Filter () [virtual]
Pure virtual destructor.
Definition at line 38 of file Filter.cpp.
References Filter::algorithm_, and Filter::manager_.
Member Function Documentation
Algorithm * getAlgorithm () [virtual]
Returns a pointer to the algorithm object.
Returns:
A pointer to the algorithm object.
Reimplemented in BasicFilter< A, M >.
Definition at line 53 of file Filter.cpp.
References Filter::algorithm_.
Referenced by BasicFilter< A, M >::getAlgorithm().
Manager * getManager () [virtual]
Returns a pointer to the Manager object.
Returns:
A pointer to the Manager object.
Reimplemented in BasicFilter< A, M >.
Definition at line 71 of file Filter.cpp.
References Filter::manager_.
Referenced by BasicFilter< A, M >::getManager(), and Filter::processRequest().
std::string getName () const
Returns the name of the filter.
Returns:
The name of the filter.
Definition at line 86 of file Filter.cpp.
References Filter::name_.
Referenced by Filter::processRequest().
void processRequest (libpipe::Request & req) [virtual]
Processes a request. This method forwards the request to the Algorithm and Manager objects.
Parameters:
[in,out] req The request object.
Definition at line 45 of file Filter.cpp.
References Filter::getManager(), Filter::getName(), and Manager::processRequest().
void setAlgorithm (Algorithm * alg) [protected]
Set the algorithm that should be used for this filter.
Parameters:
[in] alg Pointer to the Algorithm object.
Definition at line 58 of file Filter.cpp.
References Filter::algorithm_, Filter::manager_, and Manager::setAlgorithm().
Referenced by BasicFilter< A, M >::BasicFilter().
void setManager (Manager * manager) [protected]
Set the manager that manages the filter.
Parameters:
[in] manager Pointer to the Manager object.
Definition at line 76 of file Filter.cpp.
References Filter::manager_.
Referenced by BasicFilter< A, M >::BasicFilter().
void setName (const std::string & name)
Set the name of the filter.
Parameters:
[in] name The name of the filter.
Definition at line 91 of file Filter.cpp.
References Filter::name_.
Member Data Documentation
Algorithm* algorithm_ [private]
A pointer to the algorithm that is part of the filter.
Definition at line 98 of file Filter.hpp.
Referenced by Filter::getAlgorithm(), Filter::setAlgorithm(), and Filter::~Filter().
Manager* manager_ [private]
A pointer to the manager that is part of the filter.
Definition at line 102 of file Filter.hpp.
Referenced by Filter::getManager(), Filter::setAlgorithm(), Filter::setManager(), and Filter::~Filter().
std::string name_ [private]
Holds the name of the filter.
Definition at line 106 of file Filter.hpp.
Referenced by Filter::getName(), and Filter::setName().
The documentation for this class was generated from the following files:
/Users/david/Desktop/ETHZ/1_Master/Boston/libpipe/include/libpipe/ctc/Filter.hpp
/Users/david/Desktop/ETHZ/1_Master/Boston/libpipe/src/ctc/Filter.cpp