libpipe: Pipeline Class Reference
Pipeline Class Reference
Code related to the compile-time configuration
Public Member Functions
void push (const libpipe::Request &req, boost::shared_ptr< Filter > filter)
void run ()
Static Public Member Functions
static void addTrace (const std::string &t)
static void clearTrace ()
static std::vector< std::string > & getTrace ()
static bool getTraceFlag ()
static void setTraceFlag (const bool tf)
Private Attributes
std::queue< boost::shared_ptr
< Filter > > pipelineQueue_
std::queue< Request > requestQueue_
Static Private Attributes
static std::vector< std::string > trace_
static bool traceFlag_
Detailed Description
A class which holds the libpipe pipeline.
Definition at line 49 of file Pipeline.hpp.
Member Function Documentation
void addTrace (const std::string & t) [static]
Add trace information to the request object. Currently the request object simply collects std::strings.
Parameters:
[in] t Trace information.
Definition at line 88 of file Pipeline.cpp.
References vector< _Tp, _Alloc >::push_back(), and Pipeline::trace_.
void clearTrace () [static]
Clears all trace information from the Request object.
Definition at line 99 of file Pipeline.cpp.
References vector< _Tp, _Alloc >::clear(), and Pipeline::trace_.
std::vector< std::string > & getTrace () [static]
Returns all traces collected in the Request object.
Returns:
trace All collected trace information.
Definition at line 83 of file Pipeline.cpp.
References Pipeline::trace_.
bool getTraceFlag () [static]
Returns the state of the trace flag. If the trace flag is on, clients should add trace information while processing the request, using addTrace().
Returns:
The state if the trace flag (true == on).
Definition at line 73 of file Pipeline.cpp.
References Pipeline::traceFlag_.
Referenced by Pipeline::run().
void push (const libpipe::Request & req, boost::shared_ptr< Filter > filter)
Add a filter and request on top of the queue.
Parameters:
req The Request which will be processed by the filter
filter The filter which handles the request.
Definition at line 41 of file Pipeline.cpp.
References Pipeline::pipelineQueue_, queue< _Tp, _Sequence >::push(), and Pipeline::requestQueue_.
void run ()
Will run all requests in the queue. This needs to be called to run Libpipe.
Definition at line 48 of file Pipeline.cpp.
References queue< _Tp, _Sequence >::empty(), queue< _Tp, _Sequence >::front(), Pipeline::getTraceFlag(), Request::getType(), Pipeline::pipelineQueue_, queue< _Tp, _Sequence >::pop(), and Pipeline::requestQueue_.
void setTraceFlag (const bool tf) [static]
Set the state of the trace flag. This allows to switch tracing on and off.
Parameters:
[in] tf The new trace flag setting (true == on).
Definition at line 78 of file Pipeline.cpp.
References Pipeline::traceFlag_.
Member Data Documentation
std::queue<boost::shared_ptr<Filter> > pipelineQueue_ [private]
The Filters which will called
Definition at line 96 of file Pipeline.hpp.
Referenced by Pipeline::push(), and Pipeline::run().
std::queue<Request> requestQueue_ [private]
The request with which the Filters will be called
Definition at line 99 of file Pipeline.hpp.
Referenced by Pipeline::push(), and Pipeline::run().
std::vector< std::string > trace_ [static, private]
Trace information.
Definition at line 110 of file Pipeline.hpp.
Referenced by Pipeline::addTrace(), Pipeline::clearTrace(), and Pipeline::getTrace().
bool traceFlag_ [static, private]
Trace status. If true, clients receiving the request should store trace information using addTrace().
See also:
addTrace
Definition at line 106 of file Pipeline.hpp.
Referenced by Pipeline::getTraceFlag(), and Pipeline::setTraceFlag().
The documentation for this class was generated from the following files:
/Users/david/Desktop/ETHZ/1_Master/Boston/libpipe/include/libpipe/ctc/Pipeline.hpp
/Users/david/Desktop/ETHZ/1_Master/Boston/libpipe/src/ctc/Pipeline.cpp