libpipe: Handler Class Reference
Handler Class Reference
Public Member Functions
virtual ~Handler ()
void connect (Algorithm *alg, const std::string &algPortIdentifier, const std::string &thisPortIdentifier)
const timeval & getMTime () const
boost::shared_ptr< Data > getPort (const std::string &portIdentifier) const
bool needUpdate () const
void processRequest (Request &req)
void setMTime (const timeval &tv)
void setParameters (const libpipe::utilities::Parameters &param)
void setPort (const std::string &portIdentifier, boost::shared_ptr< Data > dataObject)
void update (libpipe::Request &req)
void updateMTime ()
Static Public Member Functions
static Algorithm * create ()
Static Public Attributes
static const timeval MAX_TIME
static const timeval MIN_TIME
Protected Attributes
libpipe::utilities::Parameters parameters_
std::map< std::string,
boost::shared_ptr< Data > > ports_
Private Member Functions
Handler ()
Static Private Member Functions
static const bool registerLoader ()
Static Private Attributes
static const bool registered_
Detailed Description
Handles the several Algorithms so that they can be executed in parallel, as the Pipeline will execute them in sequential order.
Definition at line 270 of file example-matrices.cpp.
Constructor & Destructor Documentation
virtual ~Handler () [virtual]
Destructor.
Definition at line 280 of file example-matrices.cpp.
Handler () [private]
Constructor.
Definition at line 298 of file example-matrices.cpp.
Referenced by create().
Member Function Documentation
void connect (Algorithm * alg, const std::string & algPortIdentifier, const std::string & thisPortIdentifier) [inherited]
Connects the port of this algorithm identified by thisPortIdentifier to the port of alg algorithm identified by algPortIdentifier
Parameters:
alg Algorithm which port is connected to the port of this algorithm
algPortIdentifier Identifier of the port of alg
thisPortIdentifier Identifier of the port of this algorithm
Definition at line 161 of file Algorithm.cpp.
References Algorithm::getPort(), and Algorithm::setPort().
static Algorithm* create () [static]
create Static constructor. A pointer to this function along with the name of the algorithm is registered with the Algorithm Factory.
Returns:
Pointer to a new Algorithm instance. Responsibility for allocated memory lies with the caller.
Reimplemented from Algorithm.
Definition at line 273 of file example-matrices.cpp.
References Handler().
Referenced by registerLoader().
const timeval & getMTime () const [inherited]
Return the last modification timestamp.
Returns:
The last modification timestamp.
Definition at line 84 of file Algorithm.cpp.
References lock(), and Algorithm::mTime_.
boost::shared_ptr< Data > getPort (const std::string & portIdentifier) const [inherited]
Returns a base class pointer to the data object located at the specified port.
Note:
To actually use the object, it is necessary to caryy out a make dynamic pointer cast to the actual object type, e.g.
 // assuming (*this) is a filter object
 boost::shared_ptr<Data> port = this->getPort("MyStringInput");
 typedef libpipe::rtc::SharedData<std::string> SharedString;
 SharedString sharedStr = boost::dynamic_pointer_cast<SharedString>(port);
 const std::string& str = *(sharedStr->get())
 // ...
Parameters:
portIdentifier A std::string which identifies the port one wants to use
Returns:
A shared_ptr to a LibpipeDataObject
Definition at line 122 of file Algorithm.cpp.
References map< _Key, _Tp, _Compare, _Alloc >::end(), map< _Key, _Tp, _Compare, _Alloc >::find(), lock(), and Algorithm::ports_.
Referenced by Algorithm::connect().
bool needUpdate () const [inherited]
Returns a flag that signifies if the Algorithm needs an update, irrespective of its modification time. The function essentially tests it the modification time of the algorithm is equal to Algorithm::MAX_TIME, signifying that the algorithm needs to be run and that its modification time value should be disregarded. Managers must check needUpdate prior to making use of the information delivered by getMTime. There are three major application scenarios that make use of the flag:
When algorithms are instantiated for the first time, their creation date need not coincide with the execution sequence (this is especially true for filter setups with branches). Hence, their modification time is set to Algorithm::MAX_TIME to guarantee their execution on the first call to update.
When the precursors are deleted the modification time gets set to Algorithm::MIN_TIME to guarantee that the algorithm does not update himself.
Managers in filters that act as sources (i.e. do not have any predecessor) cannot determine the need for execution by comparing Algorithm::getMTime() against their predecessor. In the event that their internal state changes, the manager needs to call this->getAlgorithm()->setMTime(Algorithm::MAX_TIME), thus enforcing an update of the source and propagation along the filter chain.
Returns:
Boolean flag that indicates the need for a call to the algorithm's update function.
Definition at line 114 of file Algorithm.cpp.
References lock(), Algorithm::MAX_TIME, and Algorithm::mTime_.
void processRequest (libpipe::Request & req) [inherited]
Processes the current request object. In most implementations, this will simply forward the request object to the update function.
Parameters:
[in,out] req A request object.
Definition at line 72 of file Algorithm.cpp.
References Request::is(), lock(), Algorithm::MIN_TIME, Algorithm::setMTime(), and Algorithm::update().
Referenced by Manager::processRequest().
static const bool registerLoader () [static, private]
registers the Algorithm in the factory
Returns:
true is registration was successful
Definition at line 305 of file example-matrices.cpp.
References create(), and Singleton< T >::instance().
void setMTime (const timeval & tv) [inherited]
Set the last modification timestamp.
Parameters:
[in] tv Timestamp.
Definition at line 92 of file Algorithm.cpp.
References lock(), and Algorithm::mTime_.
Referenced by Algorithm::processRequest().
void setParameters (const libpipe::utilities::Parameters & param) [inherited]
Set the parameters
Parameters:
param The Parameters where paramters are set to.
Definition at line 100 of file Algorithm.cpp.
References Algorithm::parameters_.
void setPort (const std::string & portIdentifier, boost::shared_ptr< Data > dataObject) [inherited]
Sets the Port to a certain LibpipeDataObject
Parameters:
portIdentifier A std::string which identifies the port one wants to set to the LibpipeDataObject dataObject
dataObject The Object the Port will point to
Definition at line 142 of file Algorithm.cpp.
References map< _Key, _Tp, _Compare, _Alloc >::end(), map< _Key, _Tp, _Compare, _Alloc >::find(), lock(), and Algorithm::ports_.
Referenced by Algorithm::connect().
void update (libpipe::Request & req) [virtual]
Does nothing. The output is provided as a constant, hence there is nothing to do.
Parameters:
[in] req The request object.
Implements Algorithm.
Definition at line 288 of file example-matrices.cpp.
void updateMTime () [inherited]
Update the modification timestamp to the current system time.
Definition at line 105 of file Algorithm.cpp.
References lock(), and Algorithm::mTime_.
Member Data Documentation
const timeval MAX_TIME [static, inherited]
Holds the maximum time value that can be represented in a timeval struct. This is necessary for initialization and for the correct behaviour of filters that act as sources.
See also:
updateMTime(), needUpdate()
Definition at line 78 of file Algorithm.hpp.
Referenced by Algorithm::needUpdate().
const timeval MIN_TIME [static, inherited]
Holds the minimum time value that can be represented in a timeval struct. This is necessary when disconnecting filter inputs.
Definition at line 83 of file Algorithm.hpp.
Referenced by Algorithm::processRequest().
libpipe::utilities::Parameters parameters_ [protected, inherited]
Stores the parameters needed by the update methode of the algorithm
Definition at line 204 of file Algorithm.hpp.
Referenced by Algorithm::setParameters(), and Source::update().
std::map<std::string, boost::shared_ptr<Data> > ports_ [protected, inherited]
Map of the ports and their std::string Identifier
Definition at line 200 of file Algorithm.hpp.
Referenced by CombineAlgorithm::CombineAlgorithm(), Algorithm::getPort(), LowercaseAlgorithm::LowercaseAlgorithm(), MatrixMulAlgorithm::MatrixMulAlgorithm(), Printer::Printer(), ROT13Algorithm::ROT13Algorithm(), Algorithm::setPort(), Source::Source(), and UppercaseAlgorithm::UppercaseAlgorithm().
const bool registered_ [static, private]
true is class is registered in Algorithm Factory
Definition at line 312 of file example-matrices.cpp.
The documentation for this class was generated from the following file:
/Users/david/Desktop/ETHZ/1_Master/Boston/libpipe/examples/example-matrices.cpp