libpipe: libpipe: libpipe::utilities Namespace Reference
libpipe::utilities Namespace Reference
Classes
class ErrorPolicyReturnNull
class ErrorPolicyThrowException
class Exception
class Factory
class Parameters
class Singleton
Functions
template<typename T >
void set_max (T &val)
template<typename T >
void set_min (T &val)
Detailed Description
Libpipe utility classes namespace.
Function Documentation
void libpipe::utilities::set_max (T & val)
Platform independent max limit for type
Parameters:
val the variable which will get the max value
Definition at line 84 of file Time.hpp.
References max().
Referenced by Algorithm::initMaxTime().
void libpipe::utilities::set_min (T & val)
Platform independent min limit for type
Parameters:
val the variable which will get the min value
Definition at line 92 of file Time.hpp.
References min().
Referenced by Algorithm::initMinTime().